/*
 Jasmine-jQuery: a set of jQuery helpers for Jasmine tests.

Version 2.1.1

https://github.com/velesin/jasmine-jquery

Copyright (c) 2010-2014 Wojciech Zawistowski, Travis Jeffery

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
(function(f,b){"undefined"!==typeof module&&module.exports&&"undefined"!==typeof exports?b(f,f.jasmine,require("jquery")):b(f,f.jasmine,f.jQuery)})(function(){return this}(),function(f,b,e){b.spiedEventsKey=function(a,c){return[e(a).selector,c].toString()};b.getFixtures=function(){return b.currentFixtures_=b.currentFixtures_||new b.Fixtures};b.getStyleFixtures=function(){return b.currentStyleFixtures_=b.currentStyleFixtures_||new b.StyleFixtures};b.Fixtures=function(){this.containerId="jasmine-fixtures";
this.fixturesCache_={};this.fixturesPath="spec/javascripts/fixtures"};b.Fixtures.prototype.set=function(a){this.cleanUp();return this.createContainer_(a)};b.Fixtures.prototype.appendSet=function(a){this.addToContainer_(a)};b.Fixtures.prototype.preload=function(){this.read.apply(this,arguments)};b.Fixtures.prototype.load=function(){this.cleanUp();this.createContainer_(this.read.apply(this,arguments))};b.Fixtures.prototype.appendLoad=function(){this.addToContainer_(this.read.apply(this,arguments))};
b.Fixtures.prototype.read=function(){for(var a=[],c=arguments,b=c.length,e=0;e<b;e++)a.push(this.getFixtureHtml_(c[e]));return a.join("")};b.Fixtures.prototype.clearCache=function(){this.fixturesCache_={}};b.Fixtures.prototype.cleanUp=function(){e("#"+this.containerId).remove()};b.Fixtures.prototype.sandbox=function(a){a=a||{};return e('<div id="sandbox" />').attr(a)};b.Fixtures.prototype.createContainer_=function(a){a=e("<div>").attr("id",this.containerId).html(a);e(document.body).append(a);return a};
b.Fixtures.prototype.addToContainer_=function(a){e(document.body).find("#"+this.containerId).append(a).length||this.createContainer_(a)};b.Fixtures.prototype.getFixtureHtml_=function(a){"undefined"===typeof this.fixturesCache_[a]&&this.loadFixtureIntoCache_(a);return this.fixturesCache_[a]};b.Fixtures.prototype.loadFixtureIntoCache_=function(a){var c=this.makeFixtureUrl_(a),b="";e.ajax({async:!1,cache:!1,url:c,dataType:"html",success:function(a,c,d){b=d.responseText}}).fail(function(a,b,d){throw Error("Fixture could not be loaded: "+
c+" (status: "+b+", message: "+d.message+")");});(e(e.parseHTML(b,!0)).find("script[src]")||[]).each(function(){e.ajax({async:!1,cache:!1,dataType:"script",url:e(this).attr("src"),success:function(a,c,d){b+="<script>"+d.responseText+"\x3c/script>"},error:function(a,b,d){throw Error("Script could not be loaded: "+c+" (status: "+b+", message: "+d.message+")");}})});this.fixturesCache_[a]=b};b.Fixtures.prototype.makeFixtureUrl_=function(a){return this.fixturesPath.match("/$")?this.fixturesPath+a:this.fixturesPath+
"/"+a};b.Fixtures.prototype.proxyCallTo_=function(a,c){return this[a].apply(this,c)};b.StyleFixtures=function(){this.fixturesCache_={};this.fixturesNodes_=[];this.fixturesPath="spec/javascripts/fixtures"};b.StyleFixtures.prototype.set=function(a){this.cleanUp();this.createStyle_(a)};b.StyleFixtures.prototype.appendSet=function(a){this.createStyle_(a)};b.StyleFixtures.prototype.preload=function(){this.read_.apply(this,arguments)};b.StyleFixtures.prototype.load=function(){this.cleanUp();this.createStyle_(this.read_.apply(this,
arguments))};b.StyleFixtures.prototype.appendLoad=function(){this.createStyle_(this.read_.apply(this,arguments))};b.StyleFixtures.prototype.cleanUp=function(){for(;this.fixturesNodes_.length;)this.fixturesNodes_.pop().remove()};b.StyleFixtures.prototype.createStyle_=function(a){a=e("<div></div>").html(a).text();a=e("<style>"+a+"</style>");this.fixturesNodes_.push(a);e("head").append(a)};b.StyleFixtures.prototype.clearCache=b.Fixtures.prototype.clearCache;b.StyleFixtures.prototype.read_=b.Fixtures.prototype.read;
b.StyleFixtures.prototype.getFixtureHtml_=b.Fixtures.prototype.getFixtureHtml_;b.StyleFixtures.prototype.loadFixtureIntoCache_=b.Fixtures.prototype.loadFixtureIntoCache_;b.StyleFixtures.prototype.makeFixtureUrl_=b.Fixtures.prototype.makeFixtureUrl_;b.StyleFixtures.prototype.proxyCallTo_=b.Fixtures.prototype.proxyCallTo_;b.getJSONFixtures=function(){return b.currentJSONFixtures_=b.currentJSONFixtures_||new b.JSONFixtures};b.JSONFixtures=function(){this.fixturesCache_={};this.fixturesPath="spec/javascripts/fixtures/json"};
b.JSONFixtures.prototype.load=function(){this.read.apply(this,arguments);return this.fixturesCache_};b.JSONFixtures.prototype.read=function(){for(var a=arguments,c=a.length,b=0;b<c;b++)this.getFixtureData_(a[b]);return this.fixturesCache_};b.JSONFixtures.prototype.clearCache=function(){this.fixturesCache_={}};b.JSONFixtures.prototype.getFixtureData_=function(a){this.fixturesCache_[a]||this.loadFixtureIntoCache_(a);return this.fixturesCache_[a]};b.JSONFixtures.prototype.loadFixtureIntoCache_=function(a){var c=
this,b=this.fixturesPath.match("/$")?this.fixturesPath+a:this.fixturesPath+"/"+a;e.ajax({async:!1,cache:!1,dataType:"json",url:b,success:function(b){c.fixturesCache_[a]=b},error:function(a,c,d){throw Error("JSONFixture could not be loaded: "+b+" (status: "+c+", message: "+d.message+")");}})};b.JSONFixtures.prototype.proxyCallTo_=function(a,c){return this[a].apply(this,c)};b.jQuery=function(){};b.jQuery.browserTagCaseIndependentHtml=function(a){return e("<div/>").append(a).html()};b.jQuery.elementToString=
function(a){return e(a).map(function(){return this.outerHTML}).toArray().join(", ")};var g={},n=[];b.jQuery.events={spyOn:function(a,c){var d=function(d){var e="undefined"!==typeof g[b.spiedEventsKey(a,c)]?g[b.spiedEventsKey(a,c)].calls:0;g[b.spiedEventsKey(a,c)]={args:b.util.argsToArray(arguments),calls:++e}};e(a).on(c,d);n.push(d);return{selector:a,eventName:c,handler:d,reset:function(){delete g[b.spiedEventsKey(a,c)]},calls:{count:function(){return g[b.spiedEventsKey(a,c)]?g[b.spiedEventsKey(a,
c)].calls:0},any:function(){return g[b.spiedEventsKey(a,c)]?!!g[b.spiedEventsKey(a,c)].calls:!1}}}},args:function(a,c){var d=g[b.spiedEventsKey(a,c)].args;if(!d)throw"There is no spy for "+c+" on "+a.toString()+". Make sure to create a spy using spyOnEvent.";return d},wasTriggered:function(a,c){return!!g[b.spiedEventsKey(a,c)]},wasTriggeredWith:function(a,c,d,e,f){a=b.jQuery.events.args(a,c).slice(1);"[object Array]"!==Object.prototype.toString.call(d)&&(a=a[0]);return e.equals(a,d,f)},wasPrevented:function(a,
c){var d=g[b.spiedEventsKey(a,c)];return(d=(d=b.util.isUndefined(d)?{}:d.args)?d[0]:void 0)&&d.isDefaultPrevented()},wasStopped:function(a,c){var d=g[b.spiedEventsKey(a,c)];return(d=(d=b.util.isUndefined(d)?{}:d.args)?d[0]:void 0)&&d.isPropagationStopped()},cleanUp:function(){g={};n=[]}};var m=function(a,c){return void 0===c?void 0!==a:a===c};beforeEach(function(){b.addMatchers({toHaveClass:function(){return{compare:function(a,c){return{pass:e(a).hasClass(c)}}}},toHaveCss:function(){return{compare:function(a,
c){var b=/[\s;"']/g,k;for(k in c){var f=c[k];if("auto"!==f||"auto"!==e(a).get(0).style[k]){var g=e(a).css(k).replace(b,"");f=f.replace(b,"");if(g!==f)return{pass:!1}}}return{pass:!0}}}},toBeVisible:function(){return{compare:function(a){return{pass:e(a).is(":visible")}}}},toBeHidden:function(){return{compare:function(a){return{pass:e(a).is(":hidden")}}}},toBeSelected:function(){return{compare:function(a){return{pass:e(a).is(":selected")}}}},toBeChecked:function(){return{compare:function(a){return{pass:e(a).is(":checked")}}}},
toBeEmpty:function(){return{compare:function(a){return{pass:e(a).is(":empty")}}}},toBeInDOM:function(){return{compare:function(a){return{pass:e.contains(document.documentElement,e(a)[0])}}}},toExist:function(){return{compare:function(a){return{pass:e(a).length}}}},toHaveLength:function(){return{compare:function(a,b){return{pass:e(a).length===b}}}},toHaveAttr:function(){return{compare:function(a,b,d){return{pass:m(e(a).attr(b),d)}}}},toHaveProp:function(){return{compare:function(a,b,d){return{pass:m(e(a).prop(b),
d)}}}},toHaveId:function(){return{compare:function(a,b){return{pass:e(a).attr("id")==b}}}},toHaveHtml:function(){return{compare:function(a,c){return{pass:e(a).html()==b.jQuery.browserTagCaseIndependentHtml(c)}}}},toContainHtml:function(){return{compare:function(a,c){var d=e(a).html(),f=b.jQuery.browserTagCaseIndependentHtml(c);return{pass:0<=d.indexOf(f)}}}},toHaveText:function(){return{compare:function(a,b){var c=e(a).text(),f=e.trim(c);return b&&e.isFunction(b.test)?{pass:b.test(c)||b.test(f)}:
{pass:c==b||f==b}}}},toContainText:function(){return{compare:function(a,b){var c=e.trim(e(a).text());return b&&e.isFunction(b.test)?{pass:b.test(c)}:{pass:-1!=c.indexOf(b)}}}},toHaveValue:function(){return{compare:function(a,b){return{pass:e(a).val()===b}}}},toHaveData:function(){return{compare:function(a,b,d){return{pass:m(e(a).data(b),d)}}}},toContainElement:function(){return{compare:function(a,b){return{pass:e(a).find(b).length}}}},toBeMatchedBy:function(){return{compare:function(a,b){return{pass:e(a).filter(b).length}}}},
toBeDisabled:function(){return{compare:function(a,b){return{pass:e(a).is(":disabled")}}}},toBeFocused:function(a){return{compare:function(a,b){return{pass:e(a)[0]===e(a)[0].ownerDocument.activeElement}}}},toHandle:function(){return{compare:function(a,b){if(!a||0===a.length)return{pass:!1};var c=e._data(e(a).get(0),"events");if(!c||!b||"string"!==typeof b)return{pass:!1};var f=b.split("."),g=f.shift(),l=f.slice(0).sort();l=new RegExp("(^|\\.)"+l.join("\\.(?:.*\\.)?")+"(\\.|$)");if(c[g]&&f.length)for(f=
0;f<c[g].length;f++){if(l.test(c[g][f].namespace))return{pass:!0}}else return{pass:c[g]&&0<c[g].length};return{pass:!1}}}},toHandleWith:function(){return{compare:function(a,b,d){if(!a||0===a.length)return{pass:!1};b=b.split(".")[0];a=e._data(e(a).get(0),"events")[b];for(b=0;b<a.length;b++)if(a[b].handler==d)return{pass:!0};return{pass:!1}}}},toHaveBeenTriggeredOn:function(){return{compare:function(a,c){var d={pass:b.jQuery.events.wasTriggered(c,a)};d.message=d.pass?"Expected event "+e(a)+" not to have been triggered on "+
c:"Expected event "+e(a)+" to have been triggered on "+c;return d}}},toHaveBeenTriggered:function(){return{compare:function(a){var c=a.eventName;a=a.selector;var d={pass:b.jQuery.events.wasTriggered(a,c)};d.message=d.pass?"Expected event "+c+" not to have been triggered on "+a:"Expected event "+c+" to have been triggered on "+a;return d}}},toHaveBeenTriggeredOnAndWith:function(a,c){return{compare:function(d,e,f){var g=b.jQuery.events.wasTriggered(e,d),h={pass:g&&b.jQuery.events.wasTriggeredWith(e,
d,f,a,c)};g?(e=b.jQuery.events.args(e,d,f)[1],h.message=h.pass?"Expected event "+d+" not to have been triggered with "+b.pp(f)+" but it was triggered with "+b.pp(e):"Expected event "+d+" to have been triggered with "+b.pp(f)+"  but it was triggered with "+b.pp(e)):h.message=h.pass?"Expected event "+d+" not to have been triggered on "+e:"Expected event "+d+" to have been triggered on "+e;return h}}},toHaveBeenPreventedOn:function(){return{compare:function(a,c){var d={pass:b.jQuery.events.wasPrevented(c,
a)};d.message=d.pass?"Expected event "+a+" not to have been prevented on "+c:"Expected event "+a+" to have been prevented on "+c;return d}}},toHaveBeenPrevented:function(){return{compare:function(a){var c=a.eventName;a=a.selector;var d={pass:b.jQuery.events.wasPrevented(a,c)};d.message=d.pass?"Expected event "+c+" not to have been prevented on "+a:"Expected event "+c+" to have been prevented on "+a;return d}}},toHaveBeenStoppedOn:function(){return{compare:function(a,c){var d={pass:b.jQuery.events.wasStopped(c,
a)};d.message=d.pass?"Expected event "+a+" not to have been stopped on "+c:"Expected event "+a+" to have been stopped on "+c;return d}}},toHaveBeenStopped:function(){return{compare:function(a){var c=a.eventName;a=a.selector;var d={pass:b.jQuery.events.wasStopped(a,c)};d.message=d.pass?"Expected event "+c+" not to have been stopped on "+a:"Expected event "+c+" to have been stopped on "+a;return d}}}});b.getEnv().addCustomEqualityTester(function(a,c){if(a&&c){if(a instanceof e||b.isDomNode(a)){var d=
e(a);return c instanceof e?d.length==c.length&&d.is(c):d.is(c)}if(c instanceof e||b.isDomNode(c))return d=e(c),a instanceof e?a.length==d.length&&d.is(a):d.is(a)}});b.getEnv().addCustomEqualityTester(function(a,b){if(a instanceof e&&b instanceof e&&a.size()==b.size())return a.is(b)})});afterEach(function(){b.getFixtures().cleanUp();b.getStyleFixtures().cleanUp();b.jQuery.events.cleanUp()});f.readFixtures=function(){return b.getFixtures().proxyCallTo_("read",arguments)};f.preloadFixtures=function(){b.getFixtures().proxyCallTo_("preload",
arguments)};f.loadFixtures=function(){b.getFixtures().proxyCallTo_("load",arguments)};f.appendLoadFixtures=function(){b.getFixtures().proxyCallTo_("appendLoad",arguments)};f.setFixtures=function(a){return b.getFixtures().proxyCallTo_("set",arguments)};f.appendSetFixtures=function(){b.getFixtures().proxyCallTo_("appendSet",arguments)};f.sandbox=function(a){return b.getFixtures().sandbox(a)};f.spyOnEvent=function(a,c){return b.jQuery.events.spyOn(a,c)};f.preloadStyleFixtures=function(){b.getStyleFixtures().proxyCallTo_("preload",
arguments)};f.loadStyleFixtures=function(){b.getStyleFixtures().proxyCallTo_("load",arguments)};f.appendLoadStyleFixtures=function(){b.getStyleFixtures().proxyCallTo_("appendLoad",arguments)};f.setStyleFixtures=function(a){b.getStyleFixtures().proxyCallTo_("set",arguments)};f.appendSetStyleFixtures=function(a){b.getStyleFixtures().proxyCallTo_("appendSet",arguments)};f.loadJSONFixtures=function(){return b.getJSONFixtures().proxyCallTo_("load",arguments)};f.getJSONFixture=function(a){return b.getJSONFixtures().proxyCallTo_("read",
arguments)[a]}});